### ISSUE TITLE
smartavan is disconnected after several weeks

### ISSUE THREAD

**Issue by paleos** [smartavan/smartavan-heater-controller#1]
After several weeks when smartavan was connected, properly configured and integrated to the HA it is diconnected. In truma dislplay under INDEX there is not 3rd item T23.x.x. 

RESET in the truma display doesn't help (I've tried several times including switching off power and so on). The IP address assigned by DHCP (and made static on the DHCP server) doesn't respond to HTTP requests and doesn't respond to ping requests. 

I've tried to switch off power for several minutes. It din't help also.

Wifi network smartavan-heater-XXXXX is not also available.

Is it possible somehow to FACTORY RESET the Smartavan??? I didn't find any RESET button only USB interface.

thx

**Comment by savikko** [comment]
Hi, this sounds weird.

I think first thing to try would be to upload firmware again there with USB-C.

Basically like this:
1. Install ESPHome to your computer (https://esphome.io/guides/installing_esphome.html)
2. Copy the initial configuration (https://raw.githubusercontent.com/smartavan/smartavan-heater-controller/main/smartavan-heater-controller.yaml) to some folder
3. Connect Smartavan to your computer with USB-C cable (it should be just normal serial port then)
4. Run `esphome upload smartavan-heater-controller.yaml`

That should upload firmware there. If it succeeds, it should work then. If not, then lets figure out something else.
That

**Comment by savikko** [comment]
Just to add here. I had similar type of issue here on my own environment. Not yet sure what has really happened, but there might be some overvoltage issues related.

Anyways, uploading firmware again resolved the issue.

Still, I am eager to find out what really went wrong here.

**Comment by paleos** [comment]
Hi Tomi, thanks for tip. I will try to upload the firmware and I will let you know. (maybe it has to do with the fact that everything was turned off for 2 weeks, because I was out w/o car and I was afraid that battery could be drained during the 2 weeks)

**Comment by paleos** [comment]
Hi Tommi, uploading firmware helped!!!
Just now it is working again.

thx a lot
pavel

**Comment by savikko** [comment]
> Hi Tommi, uploading firmware helped!!! Just now it is working again.

That is great!

Still, not sure what has actually happened there. It should not be normal that firmware is just lost there..

**Comment by savikko** [comment]
@paleos : We probably got this solved.
This is actually problem with the schematics and we are quite surprised that we did not realize this earlier. We are very sorry for the inconvenience we have caused here.

So, there are cases when ESP32 can stick to bootloader and it can be fixed by removing one component from the board. Yep, might sound scary, but basically instructions:

1. Disconnect board from power
2. Open up the enclosure (four cross-head screws)
3. Take PCB out
4. With small flat-head screwdriver, remove the C18 (video: https://youtube.com/shorts/g-wZhWLaOjk)

Then it is done and it problem should not occur anymore.

We will notify later all our customers about this.

**Comment by 7wells** [comment]
@savikko 
Maybe you would like to point out to the latest recommendations that were kindly provided to the users. I understood that we should not take out the PCB but wait for further instructions. Correct?

**Comment by savikko** [comment]
> @savikko Maybe you would like to point out to the latest recommendations that were kindly provided to the users. I understood that we should not take out the PCB but wait for further instructions. Correct?

Yep totally, thanks for reminding.

We are in process of creating little bit modified PCBs.

Basically, if Heater Controller happens to go state where it is not responding, there is actually the most easiest way to boot that:
1. Remove 12VDC power (input)
2. Connect USB cable (with power
3. Connect 12VDC power back
4. Remove USB cable

Now it is booting again.

What is good here is that Truma is most usually connected permanently to 12VDC so this glitch does not occur often.

As we get new PCBs, we are sending those to customers after we confirm its operation.

**Comment by paleos** [comment]
Hi, do you have already new PCBs as you promised? I've tried you reach on email but I was not successful. Thanks

**Comment by 7wells** [comment]
> Hi, do you have already new PCBs as you promised? I've tried you reach on email but I was not successful. Thanks

I don't expect any further feedback from them, as I never received any reply to my emails. 

Read what they have on their shop:

> NOTE: Deliveries paused for a while, investigating hardware issue. Deliveries will resume approximately early November 2024.

🥴

**Comment by 7wells** [comment]
@savikko 
Are you still reading here? Any news about these problems and how to mitigate them? Any hardware revisions planned?
