### ISSUE TITLE
Fatal error/failed config: ambiguous argument 'HEAD': unknown revision or path not in the working tree

### ISSUE THREAD

**Issue by 7wells** [smartavan/smartavan-heater-controller#4]
Dear Smartavan Team,

When trying to install your [Truma.yaml](https://github.com/smartavan/smartavan-heater-controller/blob/main/smartavan-heater-controller-truma.yaml) code onto my Smartavan heater controller (connected via USB-C to my PC, which has access to my Home Assistant instance with ESPHome), I get the following error message in ESPHome (MAC address redacted):
```
INFO ESPHome 2024.9.1
INFO Reading configuration /config/esphome/esphome-web-xxxxxx.yaml...
Failed config

external_components: [source /config/esphome/esphome-web-xxxxxx.yaml:6]
  - 
    fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
    Use '--' to separate paths from revisions, like this:
    'git <command> [<revision>...] -- [<file>...]'.
    source: github://Fabian-Schmidt/esphome-truma_inetbox
    components: 
      - truma_inetbox
      - uart
    refresh: always
```
Can you please explain to me what this means and how I can flash the code to my Smartavan heater controller?

I don't understand the advice `Use '--' to separate paths from revisions`.

Thanks for your help! 👍

Kind regards
7wells

**Comment by savikko** [comment]
This seems weird.

First of all, when building esphome, it is not required to have connection to HA (as only the compiled ESPHome device will connect to it). This just to clear out the confusion :)

But, there is some problem getting the esphome-truma_inetbox components from that git repo. 

What kind of modifications you have done to original esphome config? I just tried to compile it myself (with same ESPHome 2024.9.1, but on Mac) and it succeeded completely.

**Comment by 7wells** [comment]
> What kind of modifications you have done to original esphome config?

I am not even sure how I could modify my original esphome config. Can you please point me into the right direction, where I should have a closer look? Thanks a lot for your patience and help! ❤️

PS1: Other projects run fine within ESPHome.

PS2: After deinstalling the ESPHome addon in HA and installing it new, it worked. However, after I installed a slightly modified code (which was flashed successfully within HA/ESHPHome, I tried to flash again (just for testing pruposes) the code from your repo, but that failed again. This time, with this error message:
```
INFO ESPHome 2024.9.1
INFO Reading configuration /config/esphome/esphome-web-xxxxxx.yaml...
INFO Updating https://github.com/Fabian-Schmidt/esphome-truma_inetbox.git@None
INFO Detected timezone 'Europe/Berlin'
INFO Generating C++ source...
INFO Compiling app...
Processing smartavan-heater (board: esp32dev; framework: arduino; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
MissingPackageManifestError: Could not find one of 'package.json' manifest files in the package
```

I'm really sorry to bother you. I'm not sure if it's me doing something wrong or some other cause. As my other ESPHome projects show no problems when flashing, this leaves me puzzled.
